# Project identification
sonar.projectKey=pharmacyLaravel11
sonar.projectName=Pharmacy System

# Source code location
sonar.sources=app, routes, database, resources, public

# Exclude vendor and storage
sonar.exclusions=vendor/**,storage/**,node_modules/**

# SonarQube server URL
sonar.host.url=http://localhost:9000

# Authentication token (from SonarQube)
sonar.token=sqp_a8783c8e27bcf3b16dece73bb88a763f47cba6d4

# PHP language settings
sonar.language=php
